### PR TITLE
Adding CMakeLists and changing lcm package name to 'cars'

### PR DESCRIPTION
**Pull request by crogers3**

### CODE REVIEW

**Comment by psiorx** [comment]
I think we should leave the auto-generated header out and just include the .lcm file.  Once checked out, lcm-gen should be run locally to regenerate it.

**Comment by crogers3** [comment]
Done

**Comment by psiorx** [comment]
Thanks.  I'll wait for the updated struct names before merging this.

**Comment by crogers3** [comment]
Done

**Pull request merged**
